general.import = [
    "~/.config/alacritty/themes/tokyo-night.toml",
    #"~/.config/alacritty/themes/atom_one_light.toml"
]

[font]
normal = { family = "Fira Code", style = "Regular" }
bold = { family = "Fira Code", style = "Bold" }
italic = { family = "Fira Code", style = "Italic" }

[window]
opacity = 0.98
